/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_v1_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/classify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Classify */
        post: operations["classify_v1_classify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/patent-risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Patent Risk */
        post: operations["patent_risk_v1_patent_risk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/abs-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abs Check */
        post: operations["abs_check_v1_abs_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tk-radar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tk Radar */
        post: operations["tk_radar_v1_tk_radar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dossier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build Dossier */
        post: operations["build_dossier_v1_dossier_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_v1_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{doc_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Pdf */
        get: operations["get_document_pdf_v1_documents__doc_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spans/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Span */
        get: operations["get_span_v1_spans__evidence_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/corpus/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Corpus Versions */
        get: operations["list_corpus_versions_v1_corpus_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/receipts/{receipt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Receipt */
        get: operations["get_receipt_v1_receipts__receipt_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/receipts/{receipt_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Receipt */
        post: operations["verify_receipt_v1_receipts__receipt_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/speech/asr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Speech Asr */
        post: operations["speech_asr_v1_speech_asr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/speech/tts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Speech Tts */
        post: operations["speech_tts_v1_speech_tts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/escalations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Escalations */
        get: operations["list_escalations_v1_escalations_get"];
        put?: never;
        /** Create Escalation */
        post: operations["create_escalation_v1_escalations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/eval/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Eval Latest */
        get: operations["eval_latest_v1_eval_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AbsActivity
         * @enum {string}
         */
        AbsActivity: "research" | "commercial_utilisation" | "ipr_application" | "transfer_results" | "export" | "cultivation_trade";
        /** AbsChecklistItem */
        AbsChecklistItem: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            authority: components["schemas"]["Authority"];
            /** Form */
            form?: string | null;
            /** Required */
            required: boolean;
            /** Exempt */
            exempt: boolean;
            /** Exempt Reason */
            exempt_reason?: string | null;
            /** Timing */
            timing?: string | null;
            /** Detail */
            detail: string;
            /** Evidence Ids */
            evidence_ids?: string[];
        };
        /** AbsPosture */
        AbsPosture: {
            /** Summary */
            summary: string;
            /** Evidence Ids */
            evidence_ids?: string[];
        };
        /** AbsRequest */
        AbsRequest: {
            applicant_type: components["schemas"]["ApplicantType"];
            /** Activity */
            activity: components["schemas"]["AbsActivity"][];
            /** Resources */
            resources?: components["schemas"]["AbsResource"][];
            /** Ipr Type */
            ipr_type?: string | null;
            /** As Of */
            as_of?: string | null;
            /** @default auto */
            language: components["schemas"]["Language"];
        };
        /** AbsResource */
        AbsResource: {
            /** Species */
            species: string;
            /** Is Codified Tk */
            is_codified_tk: boolean;
            /** Is Cultivated */
            is_cultivated: boolean;
            /** State */
            state?: string | null;
        };
        /** AbsResult */
        AbsResult: {
            /**
             * Type
             * @default abs
             * @constant
             */
            type: "abs";
            /** Summary */
            summary: string;
            /** Checklist */
            checklist: components["schemas"]["AbsChecklistItem"][];
            decision_path: components["schemas"]["DecisionPath"];
            /** Evidence */
            evidence: {
                [key: string]: components["schemas"]["EvidenceSpan"];
            };
            /** Receipt Id */
            receipt_id: string;
        };
        /**
         * ApplicantType
         * @enum {string}
         */
        ApplicantType: "indian_citizen" | "indian_company" | "foreign_entity" | "nri";
        /**
         * Authority
         * @enum {string}
         */
        Authority: "NBA" | "SBB" | "BMC" | "none";
        /** Body_speech_asr_v1_speech_asr_post */
        Body_speech_asr_v1_speech_asr_post: {
            /** Audio */
            audio: string;
        };
        /**
         * ClassifyCategory
         * @enum {string}
         */
        ClassifyCategory: "classical" | "proprietary" | "new_drug" | "phytopharmaceutical" | "aahar_nutraceutical" | "cosmetic";
        /** ClassifyQuestion */
        ClassifyQuestion: {
            /**
             * Type
             * @default question
             * @constant
             */
            type: "question";
            /** Question Id */
            question_id: string;
            /** Text */
            text: string;
            /** Why Asked */
            why_asked: string;
            input: components["schemas"]["QuestionInput"];
            /** Evidence Ids */
            evidence_ids?: string[];
            /** Evidence */
            evidence?: {
                [key: string]: components["schemas"]["EvidenceSpan"];
            };
            progress: components["schemas"]["Progress"];
        };
        /** ClassifyRequest */
        ClassifyRequest: {
            /** Answers */
            answers?: {
                [key: string]: string;
            };
            /** @default BOTH */
            jurisdiction: components["schemas"]["Jurisdiction"];
            /** As Of */
            as_of?: string | null;
            /** @default auto */
            language: components["schemas"]["Language"];
        };
        /** ClassifyResult */
        ClassifyResult: {
            /**
             * Type
             * @default result
             * @constant
             */
            type: "result";
            category: components["schemas"]["ClassifyCategory"];
            /** Category Label */
            category_label: string;
            /** Requirements */
            requirements: components["schemas"]["Requirement"][];
            ip_posture: components["schemas"]["IpPosture"];
            abs_posture: components["schemas"]["AbsPosture"];
            decision_path: components["schemas"]["DecisionPath"];
            /** Evidence */
            evidence: {
                [key: string]: components["schemas"]["EvidenceSpan"];
            };
            /** Receipt Id */
            receipt_id: string;
        };
        /** CorpusVersionInfo */
        CorpusVersionInfo: {
            /** Label */
            label: string;
            status: components["schemas"]["CorpusVersionStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * CorpusVersionStatus
         * @enum {string}
         */
        CorpusVersionStatus: "staged" | "live" | "retired";
        /** DecisionEdge */
        DecisionEdge: {
            /** From */
            from: string;
            /** To */
            to: string;
            /** Label */
            label: string;
        };
        /** DecisionNode */
        DecisionNode: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "question" | "outcome";
            /** Label */
            label: string;
            /** Value */
            value?: string | null;
            /** Evidence Ids */
            evidence_ids?: string[];
            /**
             * Taken
             * @default true
             */
            taken: boolean;
        };
        /** DecisionPath */
        DecisionPath: {
            /** Nodes */
            nodes: components["schemas"]["DecisionNode"][];
            /** Edges */
            edges: components["schemas"]["DecisionEdge"][];
            /** Outcome Id */
            outcome_id: string;
        };
        /**
         * DocType
         * @enum {string}
         */
        DocType: "statute" | "rule" | "regulation" | "treaty" | "notification" | "case" | "guideline" | "manual";
        /** DocumentSummary */
        DocumentSummary: {
            /** Id */
            id: string;
            /** Short Key */
            short_key: string;
            /** Title */
            title: string;
            doc_type: components["schemas"]["DocType"];
            jurisdiction: components["schemas"]["Jurisdiction"];
            /** Issuer */
            issuer?: string | null;
            /** Source Url */
            source_url: string;
            /** Language */
            language: string;
            /**
             * In Force From
             * Format: date
             */
            in_force_from: string;
            /** In Force To */
            in_force_to?: string | null;
        };
        /**
         * DossierFormat
         * @enum {string}
         */
        DossierFormat: "pdf" | "docx" | "md";
        /** DossierRequest */
        DossierRequest: {
            /** Items */
            items: string[];
            /** @default pdf */
            format: components["schemas"]["DossierFormat"];
            /** @default auto */
            language: components["schemas"]["Language"];
        };
        /** EscalationRequest */
        EscalationRequest: {
            /** Request Id */
            request_id: string;
            /** Contact */
            contact?: string | null;
            /** Note */
            note?: string | null;
        };
        /** EscalationResponse */
        EscalationResponse: {
            /** Ticket Id */
            ticket_id: string;
            /** Status */
            status: string;
        };
        /** EvalCondition */
        EvalCondition: {
            /** Name */
            name: string;
            /** Citation Precision */
            citation_precision: number;
            /** Citation Recall */
            citation_recall: number;
            /** Faithfulness */
            faithfulness: number;
            /** Abstention Accuracy */
            abstention_accuracy: number;
            /** Jurisdiction Leaks */
            jurisdiction_leaks: number;
        };
        /** EvalResults */
        EvalResults: {
            /** Run Id */
            run_id: string;
            /** Corpus Version */
            corpus_version: string;
            /** N Questions */
            n_questions: number;
            /** Conditions */
            conditions: components["schemas"]["EvalCondition"][];
            /** Risk Coverage */
            risk_coverage?: components["schemas"]["RiskCoveragePoint"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** EvidenceSpan */
        EvidenceSpan: {
            /** Id */
            id: string;
            /** Doc Id */
            doc_id: string;
            /** Doc Title */
            doc_title: string;
            doc_type: components["schemas"]["DocType"];
            /**
             * Jurisdiction
             * @enum {string}
             */
            jurisdiction: "IN" | "INTL";
            /** Citation Label */
            citation_label: string;
            /** Section Key */
            section_key: string;
            /** Section Path */
            section_path: string[];
            /** Page */
            page: number;
            /** Page End */
            page_end: number;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
            /** Text */
            text: string;
            /** Sha256 */
            sha256: string;
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /** Effective To */
            effective_to?: string | null;
            /** Corpus Version */
            corpus_version: string;
            /** Source Url */
            source_url: string;
            /** Pdf Url */
            pdf_url: string;
            /** Highlights */
            highlights?: components["schemas"]["Highlight"][];
        };
        /** Formulation */
        Formulation: {
            /** Name */
            name: string;
            /** Intended Use */
            intended_use: string;
            /** Product Form */
            product_form: string;
            /** Ingredients */
            ingredients: components["schemas"]["Ingredient"][];
            /** Process Summary */
            process_summary?: string | null;
            /** Classical Sources Cited */
            classical_sources_cited?: string[];
            /**
             * Claims Novel Effect
             * @default false
             */
            claims_novel_effect: boolean;
            /** Novel Effect Evidence */
            novel_effect_evidence?: string | null;
            /**
             * Has Clinical Data
             * @default false
             */
            has_clinical_data: boolean;
            /**
             * Is Derivative Of Known Substance
             * @default false
             */
            is_derivative_of_known_substance: boolean;
            resource_origin?: components["schemas"]["ResourceOrigin"] | null;
            applicant_type?: components["schemas"]["ApplicantType"] | null;
            /** Planned Actions */
            planned_actions?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Corpus Version */
            corpus_version: string;
            models: components["schemas"]["ModelsStatus"];
        };
        /** Highlight */
        Highlight: {
            /** Page */
            page: number;
            /** Page Width */
            page_width: number;
            /** Page Height */
            page_height: number;
            /**
             * Rects
             * @description Each rect is [x0, y0, x1, y1] in PDF points, origin top-left (PyMuPDF).
             */
            rects: number[][];
        };
        /** Ingredient */
        Ingredient: {
            /** Name */
            name: string;
            /** Part */
            part?: string | null;
            /** Role */
            role?: ("active" | "excipient") | null;
            /** Amount */
            amount?: string | null;
        };
        /**
         * InputKind
         * @enum {string}
         */
        InputKind: "single" | "multi" | "boolean" | "text";
        /** InputOption */
        InputOption: {
            /** Value */
            value: string;
            /** Label */
            label: string;
        };
        /** IpPosture */
        IpPosture: {
            patent: components["schemas"]["PostureItem"];
            gi: components["schemas"]["PostureItem"];
            trademark: components["schemas"]["PostureItem"];
            design: components["schemas"]["PostureItem"];
            copyright: components["schemas"]["PostureItem"];
            trade_secret: components["schemas"]["PostureItem"];
        };
        /**
         * Jurisdiction
         * @enum {string}
         */
        Jurisdiction: "IN" | "INTL" | "BOTH";
        /**
         * Language
         * @enum {string}
         */
        Language: "auto" | "en" | "hi" | "ta" | "bn" | "mr" | "te" | "gu" | "kn" | "ml" | "pa" | "or";
        /** ModelIds */
        ModelIds: {
            /** Llm */
            llm: string;
            /** Embed */
            embed: string;
            /** Nli */
            nli: string;
        };
        /** ModelsStatus */
        ModelsStatus: {
            /** Llm */
            llm: string;
            /** Embed */
            embed: string;
            /** Nli */
            nli: string;
        };
        /** NormalizedIngredient */
        NormalizedIngredient: {
            /** Input */
            input: string;
            /** Canonical Latin */
            canonical_latin: string;
            /** Sanskrit */
            sanskrit?: string | null;
            /** Regional */
            regional?: components["schemas"]["RegionalName"][];
            /** Confidence */
            confidence: number;
        };
        /** PatentRisk */
        PatentRisk: {
            /**
             * Type
             * @default patent_risk
             * @constant
             */
            type: "patent_risk";
            gauge: components["schemas"]["Risk"];
            /** Score */
            score: number;
            /** Per Section */
            per_section: components["schemas"]["PatentRiskSection"][];
            /** What Would Help */
            what_would_help?: components["schemas"]["WhatWouldHelp"][];
            decision_path: components["schemas"]["DecisionPath"];
            /** Evidence */
            evidence: {
                [key: string]: components["schemas"]["EvidenceSpan"];
            };
            /** Receipt Id */
            receipt_id: string;
            /**
             * Disclaimer
             * @default Informational, not legal advice.
             */
            disclaimer: string;
        };
        /**
         * PatentRiskRequest
         * @description Formulation + as_of/language, per §5.3: `Formulation (+ as_of, language) -> PatentRisk`.
         */
        PatentRiskRequest: {
            /** Name */
            name: string;
            /** Intended Use */
            intended_use: string;
            /** Product Form */
            product_form: string;
            /** Ingredients */
            ingredients: components["schemas"]["Ingredient"][];
            /** Process Summary */
            process_summary?: string | null;
            /** Classical Sources Cited */
            classical_sources_cited?: string[];
            /**
             * Claims Novel Effect
             * @default false
             */
            claims_novel_effect: boolean;
            /** Novel Effect Evidence */
            novel_effect_evidence?: string | null;
            /**
             * Has Clinical Data
             * @default false
             */
            has_clinical_data: boolean;
            /**
             * Is Derivative Of Known Substance
             * @default false
             */
            is_derivative_of_known_substance: boolean;
            resource_origin?: components["schemas"]["ResourceOrigin"] | null;
            applicant_type?: components["schemas"]["ApplicantType"] | null;
            /** Planned Actions */
            planned_actions?: string[];
            /** As Of */
            as_of?: string | null;
            /** @default auto */
            language: components["schemas"]["Language"];
        };
        /** PatentRiskSection */
        PatentRiskSection: {
            /** Section */
            section: string;
            risk: components["schemas"]["Risk"];
            /** Triggered Rules */
            triggered_rules?: string[];
            /** Reasons */
            reasons?: string[];
            /** Evidence Ids */
            evidence_ids?: string[];
        };
        /**
         * Persona
         * @enum {string}
         */
        Persona: "vaidya" | "startup" | "attorney" | "licensing_officer" | "researcher";
        /** PostureItem */
        PostureItem: {
            risk: components["schemas"]["Risk"];
            /** Note */
            note: string;
            /** Evidence Ids */
            evidence_ids?: string[];
        };
        /** Progress */
        Progress: {
            /** Answered */
            answered: number;
            /** Estimated Total */
            estimated_total: number;
        };
        /**
         * QueryMode
         * @enum {string}
         */
        QueryMode: "text" | "voice";
        /** QueryRequest */
        QueryRequest: {
            /** Query */
            query: string;
            /** @default BOTH */
            jurisdiction: components["schemas"]["Jurisdiction"];
            /** As Of */
            as_of?: string | null;
            /** @default auto */
            language: components["schemas"]["Language"];
            /** @default researcher */
            persona: components["schemas"]["Persona"];
            /** @default text */
            mode: components["schemas"]["QueryMode"];
            /** Conversation Id */
            conversation_id?: string | null;
            formulation?: components["schemas"]["Formulation"] | null;
        };
        /** QuestionInput */
        QuestionInput: {
            kind: components["schemas"]["InputKind"];
            /** Options */
            options?: components["schemas"]["InputOption"][];
        };
        /** RadarAxis */
        RadarAxis: {
            /** Label */
            label: string;
            /** Value */
            value: number;
        };
        /** RadarData */
        RadarData: {
            /** Axes */
            axes: components["schemas"]["RadarAxis"][];
        };
        /** Receipt */
        Receipt: {
            /** Id */
            id: string;
            /** Request Id */
            request_id: string;
            /** Corpus Version */
            corpus_version: string;
            /** Query Hash */
            query_hash: string;
            /** Chunk Hashes */
            chunk_hashes: string[];
            model_ids: components["schemas"]["ModelIds"];
            /** Prompt Version */
            prompt_version: string;
            /** Prev Hash */
            prev_hash: string;
            /** Entry Hash */
            entry_hash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RegionalName */
        RegionalName: {
            /** Lang */
            lang: string;
            /** Name */
            name: string;
        };
        /** Requirement */
        Requirement: {
            /** Text */
            text: string;
            /** Evidence Ids */
            evidence_ids?: string[];
        };
        /** ResourceOrigin */
        ResourceOrigin: {
            /** State */
            state?: string | null;
            /** Wild Or Cultivated */
            wild_or_cultivated?: ("wild" | "cultivated") | null;
            /** Codified Tk */
            codified_tk?: boolean | null;
        };
        /**
         * Risk
         * @enum {string}
         */
        Risk: "low" | "medium" | "high";
        /** RiskCoveragePoint */
        RiskCoveragePoint: {
            /** Threshold */
            threshold: number;
            /** Coverage */
            coverage: number;
            /** Risk */
            risk: number;
        };
        /** SpanVerification */
        SpanVerification: {
            /** Evidence Id */
            evidence_id: string;
            /** Sha256 */
            sha256: string;
            /** In Corpus */
            in_corpus: boolean;
            /** Merkle Proof Valid */
            merkle_proof_valid: boolean;
        };
        /** SpeechAsrResponse */
        SpeechAsrResponse: {
            /** Text */
            text: string;
            language: components["schemas"]["Language"];
        };
        /** SpeechTtsRequest */
        SpeechTtsRequest: {
            /** Text */
            text: string;
            /** @default auto */
            language: components["schemas"]["Language"];
        };
        /** TkMatch */
        TkMatch: {
            /** Formulation Id */
            formulation_id: string;
            /** Name */
            name: string;
            /** Source Text */
            source_text: string;
            /** Similarity */
            similarity: number;
            /** Overlap */
            overlap?: string[];
            /** Missing In Input */
            missing_in_input?: string[];
            /** Extra In Input */
            extra_in_input?: string[];
            /** Indication Match */
            indication_match: boolean;
            /** Evidence Ids */
            evidence_ids?: string[];
        };
        /** TkRadar */
        TkRadar: {
            /**
             * Type
             * @default tk_radar
             * @constant
             */
            type: "tk_radar";
            /** Normalized Ingredients */
            normalized_ingredients: components["schemas"]["NormalizedIngredient"][];
            /** Matches */
            matches: components["schemas"]["TkMatch"][];
            radar: components["schemas"]["RadarData"];
            tkdl_query: components["schemas"]["TkdlQuery"];
            /** Watchlist Hits */
            watchlist_hits?: components["schemas"]["WatchlistHit"][];
            /** Receipt Id */
            receipt_id: string;
        };
        /** TkdlQuery */
        TkdlQuery: {
            /** Terms */
            terms: string[];
            /** Ipc */
            ipc: string[];
            /** Text */
            text: string;
            /**
             * Note
             * @default TKDL access is restricted; this pack is for use by an authorised examiner or via the applicant's counsel.
             */
            note: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyResult */
        VerifyResult: {
            /** Chain Valid */
            chain_valid: boolean;
            /** Corpus Root */
            corpus_root: string;
            /** Spans */
            spans?: components["schemas"]["SpanVerification"][];
        };
        /** WatchlistHit */
        WatchlistHit: {
            /** Case */
            case: string;
            jurisdiction: components["schemas"]["Jurisdiction"];
            /** Summary */
            summary: string;
            /** Outcome */
            outcome: string;
            /** Source Url */
            source_url: string;
        };
        /** WhatWouldHelp */
        WhatWouldHelp: {
            /** Text */
            text: string;
            /** Evidence Ids */
            evidence_ids?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    query_v1_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    classify_v1_classify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassifyQuestion"] | components["schemas"]["ClassifyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patent_risk_v1_patent_risk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatentRiskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatentRisk"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abs_check_v1_abs_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AbsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbsResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tk_radar_v1_tk_radar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Formulation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TkRadar"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_dossier_v1_dossier_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DossierRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_v1_documents_get: {
        parameters: {
            query?: {
                jurisdiction?: components["schemas"]["Jurisdiction"] | null;
                doc_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_pdf_v1_documents__doc_id__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_span_v1_spans__evidence_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceSpan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_corpus_versions_v1_corpus_versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusVersionInfo"][];
                };
            };
        };
    };
    get_receipt_v1_receipts__receipt_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                receipt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_receipt_v1_receipts__receipt_id__verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                receipt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    speech_asr_v1_speech_asr_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_speech_asr_v1_speech_asr_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeechAsrResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    speech_tts_v1_speech_tts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeechTtsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_escalations_v1_escalations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    create_escalation_v1_escalations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EscalationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscalationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eval_latest_v1_eval_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalResults"];
                };
            };
        };
    };
}
